name: Build and test on PR
on:
  # This workflow will only run for pull requests targeting the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  test:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test